package org.vld.books.security

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer

class SecurityWebApplicationInitializer : AbstractSecurityWebApplicationInitializer()